/*
 * action types
 */

export const MODEL_COMPONENT_DEFAULT_STATE = 'MODEL_COMPONENT_DEFAULT_STATE';
export const MODEL_INPUT_VALIDATION = 'MODEL_INPUT_VALIDATION';
export const MODEL_FORM_VALIDATION = 'MODEL_FORM_VALIDATION';